site_author: hassaku63
site_name: Excel方眼紙で手順書作るのやめ隊
repo_name: GitHub
repo_url: https://github.com/hassaku63/ci_docs

docs_dir: docs
site_dir: site

use_directory_urls: false

theme:
    name: material

pages:
  - Home: index.md
  - "Qiita Post (2/25)": 20180225_qiita_blog.md
