version: 2
jobs:
  build-job:
    docker:
      - image: hassaku63/ci-docs_build_environment
    working_directory: /tmp/ci_docs
    steps:
      - checkout
      - run:
        name: Install awscli
        command: pip install awscli
      - run:
        name: mkdocs build
        command: mkdocs build

  deploy-job:
    docker:
      - image: hassaku63/ci-docs_build_environment
    working_directory: /tmp/ci_docs
    steps:
      - run:
        name: (Dry run) Deploy to S3 website hosting
        command: aws s3 sync --dryrun site/ s3://${DEPLOY_S3_BUCKET_NAME}/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
        requires:
          - build-job
        filters:
          branches:
            only: master
