version: 2

defaults: &defaults
  working_directory: /tmp/ci_docs
  docker:
    - image: hassaku63/ci-docs_build_environment
  environment:
    - DEPLOY_S3_BUCKET_NAME: ci-docs.hassaku.net

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: mkdocs build
      - persist_to_workspace:
          root: .
          paths:
            - site

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: site
      - run: pip install awscli
      #- run: echo $(pwd)
      #- run: echo $(ls)
      - run: aws s3 sync --dryrun site/ s3://${DEPLOY_S3_BUCKET_NAME}/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
