version: 2
jobs:
  build:
    docker:
      - image: hassaku63/ci-docs_build_environment
    working_directory: /tmp/ci_docs
    steps:
      - checkout
      - run:
        name: mkdocs build
        command: |
          pip install awscli
          mkdocs build

  deploy:
    docker:
      - image: hassaku63/ci-docs_build_environment
    working_directory: /tmp/ci_docs
    steps:
      - run:
        - name: (Dry run) Deploy to S3 website hosting
        - command: aws s3 sync --dryrun site/ s3://${DEPLOY_S3_BUCKET_NAME}/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master
