version: 2
jobs:
  build-job:
    docker:
      - image: hassaku63/ci-docs_build_environment
    working_directory: /tmp/ci_docs
    steps:
      - checkout
      - run:
        command: |
          pip install awscli
          command: mkdocs build
      - deploy:
        command: aws s3 sync --dryrun site/ s3://${DEPLOY_S3_BUCKET_NAME}/
