version: 2

defaults: &defaults
  working_directory: /tmp/ci_docs
  docker:
    - image: hassaku63/ci-docs_build_environment
  environment:
    #- DEPLOY_S3_BUCKET_NAME: ci-docs.hassaku.net

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: mkdocs build
      - persist_to_workspace:
          root: .
          paths:
            - site
      - store_artifacts:
          path: /tmp/ci_docs/site

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/website
      - run: pip install awscli
      - run: aws s3 sync --exact-timestamp --delete /tmp/website/site/ s3://${DEPLOY_S3_BUCKET_NAME}/

  dev_deploy_approval:
    <<: *defaults
    steps:
      - run: echo ${SLACK_WEBHOOK_URL}
      - run:
          command: |
            curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"Please approve workflow from <https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|here>.\"}" \
            ${SLACK_WEBHOOK_URL}

  dev_deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/website
      - run: pip install awscli
      - run: aws s3 sync --dryrun --exact-timestamp --delete /tmp/website/site/ s3://${DEPLOY_S3_BUCKET_NAME}/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - dev_deploy_approval:
          #type: approval
          requires:
            - build
      - dev_deploy:
          type: approval
          requires:
            - dev_deploy_approval
          filters:
            branches:
              only: develop
